In [ ]:
# Import required libraries

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [5]:
# Load the dataset
df = pd.read_csv("../data/Heart_Disease_Prediction.csv")
# Display the first 5 rows
print(df.head())
# Display dataset shape
print("\nDataset Shape:", df.shape)

   Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2
1   67    0                3  115          564             0            2
2   57    1                2  124          261             0            0
3   64    1                4  128          263             0            0
4   74    0                2  120          269             0            2

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2
1     160                0            1.6            2
2     141                0            0.3            1
3     105                1            0.2            2
4     121                1            0.2            1

   Number of vessels fluro  Thallium Heart Disease
0                        3         3      Presence
1                        0         7       Absence
2                        0         7      Presence
3                        1         7       Absence
4                        1         3       Absence

Dataset Shape: (270, 14)

In [6]:
# Display basic information about the dataset

print("Dataset Shape:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nDataset Information:")
df.info()
print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape:
(270, 14)

Column Names:
Index(['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease'],
      dtype='object')

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease            270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

Missing Values:
Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [7]:
# Check unique values in the target column

print("Unique values in Heart Disease column:")
print(df["Heart Disease"].unique())

Unique values in Heart Disease column:
['Presence' 'Absence']

In [8]:
# Convert target variable into numeric values

df["Heart Disease"] = df["Heart Disease"].map({
    "Presence": 1,
    "Absence": 0
})

# Verify the conversion

print("After Conversion:")
print(df["Heart Disease"].unique())

After Conversion:
[1 0]

In [9]:
print("\nTarget Variable Count:")
print(df["Heart Disease"].value_counts())

Target Variable Count:
Heart Disease
0    150
1    120
Name: count, dtype: int64

In [11]:
# Separate input features (X) and target variable (y)

X = df.drop("Heart Disease", axis=1)
y = df["Heart Disease"]

# the shape of X and y
print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

# first 5 rows of features
print("\nFeatures (X):")
display(X.head())

#  first 5 target values
print("\nTarget Variable (y):")
display(y.head())

Features Shape: (270, 13)
Target Shape: (270,)

Features (X):

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3

Target Variable (y):

0    1
1    0
2    1
3    0
4    0
Name: Heart Disease, dtype: int64

In [12]:
# Split the dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display the shape of the training and testing data

print("Training Features Shape:", X_train.shape)
print("Testing Features Shape:", X_test.shape)

print("Training Target Shape:", y_train.shape)
print("Testing Target Shape:", y_test.shape)

Training Features Shape: (216, 13)
Testing Features Shape: (54, 13)
Training Target Shape: (216,)
Testing Target Shape: (54,)

In [14]:
# Create the Logistic Regression model

model = LogisticRegression(max_iter=1000, random_state=42)
# Train the model

model.fit(X_train, y_train)

print("Model trained successfully!")

Model trained successfully!

/Users/icg/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
# Make predictions on the test data

y_pred = model.predict(X_test)

# Calculate model accuracy

accuracy = accuracy_score(y_test, y_pred)

# Display accuracy

print(f"Model Accuracy: {accuracy * 100:.2f}%")

Model Accuracy: 92.59%

In [16]:
# Compare Actual vs Predicted values

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})

comparison.head(10)

   Actual  Predicted
0       1          1
1       1          1
2       0          0
3       0          0
4       0          0
5       1          1
6       0          1
7       0          0
8       0          0
9       0          0

In [17]:
# summary of the project
print("Heart Disease Prediction using Logistic Regression")
print("Algorithm Used : Logistic Regression")
print(f"Model Accuracy : {accuracy * 100:.2f}%")
print("Project Completed Successfully!")

Heart Disease Prediction using Logistic Regression
Algorithm Used : Logistic Regression
Model Accuracy : 92.59%
Project Completed Successfully!